### ISSUE TITLE
Puppet 6.11.0 is breaking monkey patches for Puppet::Pops::Loader::NullLoader

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-editor-services#199]
```
  1) PuppetLanguageServerSidecar with Feature Flag puppetstrings when running default_aggregate action should return a cachable deserializable aggregate object with all default metadata
     Failure/Error: raise "Expected exit code of 0, but got #{status.exitstatus} #{_stderr}" unless status.exitstatus.zero?

     RuntimeError:
       Expected exit code of 0, but got 1 C:/Source/puppet-editor-services/lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb:79:in `<module:Loader>': uninitialized constant Puppet::Pops::Loader::NullLoader (NameError)
        from C:/Source/puppet-editor-services/lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb:78:in `<module:Pops>'
        from C:/Source/puppet-editor-services/lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb:77:in `<module:Puppet>'
        from C:/Source/puppet-editor-services/lib/puppet-languageserver-sidecar/puppet_monkey_patches_puppetstrings.rb:76:in `<top (required)>'
        from C:/Source/puppet-editor-services/lib/puppet_languageserver_sidecar.rb:97:in `require'
        from C:/Source/puppet-editor-services/lib/puppet_languageserver_sidecar.rb:97:in `block in require_gems'
        from C:/Source/puppet-editor-services/lib/puppet_languageserver_sidecar.rb:95:in `each'
        from C:/Source/puppet-editor-services/lib/puppet_languageserver_sidecar.rb:95:in `require_gems'
        from C:/Source/puppet-editor-services/lib/puppet_languageserver_sidecar.rb:209:in `init_puppet_sidecar'
        from puppet-languageserver-sidecar:11:in `<main>'
     # ./spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb:20:in `run_sidecar'
     # ./spec/languageserver-sidecar/integration/puppet-languageserver-sidecar/featureflag_puppetstrings/featureflag_puppetstrings_spec.rb:101:in `block (3 levels) in <top (required)>'

Finished in 3.22 seconds (files took 11.24 seconds to load)
1 example, 1 failure

Failed examples:
```

**Comment by glennsarti** [comment]
Removed in https://github.com/puppetlabs/puppet/pull/7619

**Comment by glennsarti** [comment]
Source is here

https://github.com/puppetlabs/puppet/blob/6.10.1/lib/puppet/pops/loader/null_loader.rb

**Comment by glennsarti** [comment]
Hrmmm also it appears the Puppet Stack has been modified

https://github.com/puppetlabs/puppet/commit/88592b894afd436fc6f2a957c12ea2ae16463d5e

and Debug Server can longer get access to the call stack 😢😢
